name: nuclei_segmenter channels: - conda-forge - defaults

dependencies:
  # Core Python
  - python=3.10

  # Scientific stack
  - scipy
  - pandas
  - tifffile

  # UI framework
  - pyside2

  # Napari with PySide2 backend
  - pip
  - pip:
      - torch==2.10.0+cu128 torchvision==0.20.0+cu128 --index-url https://download.pytorch.org/whl/cu128
      - "napari[pyside2]"
      - cellpose
      - imaris-ims-file-reader
      - alive-progress
      - libpysal
      - esda
      - matplotlib
      - seaborn
      - tables
      - qdarktheme
