name: NucLogic
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.11

  # Scientific stack
  - numpy
  - scipy
  - pandas
  - tifffile
  - scikit-learn
  - scikit-image

  # UI framework
  - pyside2

  # Napari with PySide2 backend
  - pip
  - pip:
      - "napari[pyside2]"
      - imaris-ims-file-reader
      - alive-progress
      - libpysal
      - esda
      - matplotlib
      - seaborn
      - tables
      - pyqtdarktheme
      - opencv-python-headless
      - PyImarisWriter