# This file contains a yml description of the environment that conda can make to run this python program

name: organoid_cropper_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - alive_progress==3.2.0
    - cellpose==4.0.6
    - esda==2.7.0
    - imaris_ims_file_reader==0.1.8
    - libpysal==4.13.0
    - matplotlib==3.10.3
    - numpy==2.3.1
    - pandas==2.3.1
    - PyImarisWriter==0.7.0
    - scipy==1.16.0
    - scikit-image
    - tables==3.10.2
    - tifffile==2025.6.11
    - tkfilebrowser==2.3.2
    - trackpy==0.6.4
    - pywin32
